export const GET_EMPLOYEE_LOADING = "GET_EMPLOYEE_LOADING";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_ERROR  = "GET_EMPLOYEE_ERROR";


export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR  = "UPDATE_EMPLOYEE_ERROR";


export const ADD_EMPLOYEE_LOADING = "ADD_EMPLOYEE_LOADING";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR  = "ADD_EMPLOYEE_ERROR";